export const users = {
  ADD_USER: "ADD_USER",
  REMOVE_USER: "REMOVE_USER",
};

export const accounts = {
  ADD_ACCOUNT: "ADD_ACCOUNT",
  REMOVE_ACCOUNT: "REMOVE_ACCOUNT",
};

export const rest = {
  INCREMENT_ACCOUNT_COUNTER: "INCREMENT_ACCOUNT_COUNTER",
  INCREMENT_USER_COUNTER: "INCREMENT_USER_COUNTER",
  INVERSE_STATUS: "INVERSE_STATUS",
};


